env:
  global:
  - secure: fZn0UgO43HCCWkJEeL37gwPZylbUngLFxYfVxw23oVJpp2QcksHUJxO1pzgNyTm7GMJl3xxbYa4dK6a72oMsmPsb7xl6jA8L7kQA1Xo+J29QQLxP8WWYP2SyZNxANyyvWpmoMcVnTHZ4UYQMEMiDRNMx4b4iN8ytyQsJj5df9uTOmcr2pNcyTlLTFL1nT43q+MA8nRtKU7sVyDr037CLppxXuY+AUwenCeBHAVpBecfnizRTaItd7qfWYcw27xQZ5Z1M4b6bHWZpwSPdelRsqchLBxIhx50zbBph5xbB4Ov9d6RTcS7J9F3QxMzkCAdT0YuLiIC4TfSZExWUYoOg4/kRm7Vz0LSovmBQMW9FxrKBf7rWoafhqfT83Rz4rssquTICB68U0R4fhUNIctptYgwT2UIfBWGIRwJSGhwsrEnC626uX/bL6B5VslWg2+CjEz1tfqyg88XO/sFcr79IWtVNKuqA/CHu1SCChRlyN9Di7fzvOW7HAAwcnLyCVWNQ9qNjc2c84+ufdhxPBGJxiaeN14+9YmgggjETryMz4JM4VF+J7H5wDmEbOFmEofmb0G7B/0jtJX0i/qBaA/Ow9JDg4JZBr+JfGLRmRmnfl+P0vMgAYspVW5qmHRWXxpKHBmlrvCK+Aw/RKWJ8DiRKn7Dq8LpUpneLYtqd9uBa+CA=
  - secure: BWOZXDSg6t6ie0BWXrMj30wNQlB0IbNJkEV/KOx7rFuNVeBeSUOa69fZ1Kk7fGyhExvMY/CgAMxXIWZGYuFgP2TcITDHhFPOtNDE2k7MTqQDQ6/f4svFR8B7H9Nms0qHmHXc2UXWT+0VNvHCuoMD99zJzG5AP2H68b5um9x6LZPNOrkVwincBOpH1yL2Ed++UCQDoGSN1LjlFOOsGpMD5Q9DRldzAPOI5YqdJkHzmnVyhAbWXbDNkVm7eRqnS4WHe9sNkyAXEd1R3w+TYCaOEHarKFU2w9FqYTAlK0HriVI9BdsowNnaHAERrlwxaqLb7BuEA1j4EkowYClSmCR2tAVJqkTWYTNZXmI/vjJxdap9+PT2kwOkq4ntig7FbcV/NKXVI2ckFgF/NTFvAEoTIWOvIlRvO0Tk7zdSkfR0QnEs4kZ3JeUJpj9wrZ4ISSy6uIh3v9H/cslakAAdkuj0V3J4VGVgih3VllAj8k2mFKWFUBUK4PKmmXMVHZkeTWyqIjm56Jnb+9AaUxmj54IJw50AXqF8eizuYPO55/ZOMPPhqyNqyhCj4hQpipkzYCl25p11AIIzntlgwbEVA7GHdwnGuwXQz2OK0ZZ6QB/8Y05VduSnCB5qsXBo1OKlOSAcEwpM8aLmKcA8ZkjCjVQ3hsCqTe9vz2nTudI1HeK0DOw=
os:
- linux
- osx
osx_image: xcode11.2
dist: bionic
language: cpp
sudo: enabled
git:
  depth: 1
before_install:
  - chmod +x ./scripts/zipping.sh
install:
- "./.ci/travis/install_deps.sh"
before_script: "./.ci/travis/lint.sh"
script:
- "./scripts/build.sh"
- "./scripts/test.sh"
before_deploy:
  - "./scripts/zipping.sh"
  - git config --local user.name "TCModus"
  - git config --local user.email "thomas.collins@moduscreate.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag -f $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: UaqJzNmaL6ctrGEMcqmdO3T7RTUOujTNqDllItA1MdBUZuU7zrJXhvqVuUessfJi1B+rXm2ulWe7PzKjyqYQXVWVg/UoTkn+x47+HX8DHdOTq56V6iiwTXGhh3PnSSSYK809U6vfCS8sYeTIS+yZmguwU1XPLnk/mp8lMyhwK+ASTnRBaNfZlWiWYvsV+qi54ru/X3Ro1WuG/1ckfHDp2batte/dT3rGVbpOJ0mkA4iz5K/M0hPkLTO2Qge/XL2KxqNH/W6XhKgG8XQoi7LpzZLMCOkZzokX/QsDkSlTE40ca/PIv/YenMwbqBofajwBovmaJl0WuzMKJybj+qsAH7Z+7wpQ5fdgC2i5hDqTDf22BzwOu38xezCUS0DnStiqgAvm5NBkfoXyVVphLz0lU635dh+HinTQkW3G+xdhWpuYy7ShP3sdxjsLMW6V4Equ/c6j64BsMWh5Qdxou5aiaPswpqZ3j6ICjtEqeeWvW5+XQLrt5MUpKZVuIFOmL9zD+HQJfWZEEwTjOG0nnuUKQydvfhW7yINS1EmLdgCPoUsKTeScUlWRTHTKXmVqXIeZINQBPl91OiMj725VF+Wjh9pjuAZ3BNEhNd/BCp6JboQv69pTubU1MswZ8ma2LuSN/EstgJvFJ0j0kthso2SJe+5y9VmUEF3b9OvyZQnBoq8=
  file:
  - /home/travis/build/ModusCreateOrg/modite-adventure/build/modite-linux.zip
  - /Users/travis/build/ModusCreateOrg/modite-adventure/build/modite-mac.zip
  on:
    all_branches: true
  skip_cleanup: 'true'
notifications:
  slack:
    secure: XH59GGO2tpCt8reN1DDiuhVtKc6kMhf692Bf01HDPp2iIclvI9NJnbzyrSRpslYbt/3QBX/KNJkVkZh6HevprrWhBCXnn43vDFayh/84I5x43Qpwy+jAix1nhiw60fFkSze3Kuxqhd1u0vl87ahCmKbNkQrMPyom1D5+Ujyi0fcYwDeOLp7pHq+DexEjzCCqu/XtNLUzwB2pTCYmx3XAh8PTIE4LG1WO1uYF2XV2554BLJRIt6mGciR17x63kkCJy2NrJ2Gkve8CTknI1i/aoQWZYQzoJY8MCnpoU4565yt+bVI3eAYVEmimSqt5bai+SBwMeZ8QIZ0qGUfD53tX6C98XHFSeV+GF7TZjBbsS8m00uuuxMGZzD8dxZp9ga7ki0LeLefTGqFZsrLc++NMO0joAQNT55e6kYu/XC05Gg/fAqskGkJSD+tU5Tzhn3DYvYaGe6fIhbg4kX8u8l+Ddd6IrEwQad5G45qovEOi+AXHzM9lOpwOJ7IcBUOsZSZNAkzvonRaN4fhPE/Y5bGlw/qtc8VRN/W2xdVhEheQ67NzzbTgGzeflLe+b3pnKjNxTSMBVuLrlB9jF9PXKNcY0cuMwcqU2ImVLxe9cxlLA+qGIk866tLRRkkUMI5Kjx4S+PpGGcSVVtheEpR0cB2WsH+l17CYXE/xwuDMGpccv14=
