env:
  global:
  - secure: fZn0UgO43HCCWkJEeL37gwPZylbUngLFxYfVxw23oVJpp2QcksHUJxO1pzgNyTm7GMJl3xxbYa4dK6a72oMsmPsb7xl6jA8L7kQA1Xo+J29QQLxP8WWYP2SyZNxANyyvWpmoMcVnTHZ4UYQMEMiDRNMx4b4iN8ytyQsJj5df9uTOmcr2pNcyTlLTFL1nT43q+MA8nRtKU7sVyDr037CLppxXuY+AUwenCeBHAVpBecfnizRTaItd7qfWYcw27xQZ5Z1M4b6bHWZpwSPdelRsqchLBxIhx50zbBph5xbB4Ov9d6RTcS7J9F3QxMzkCAdT0YuLiIC4TfSZExWUYoOg4/kRm7Vz0LSovmBQMW9FxrKBf7rWoafhqfT83Rz4rssquTICB68U0R4fhUNIctptYgwT2UIfBWGIRwJSGhwsrEnC626uX/bL6B5VslWg2+CjEz1tfqyg88XO/sFcr79IWtVNKuqA/CHu1SCChRlyN9Di7fzvOW7HAAwcnLyCVWNQ9qNjc2c84+ufdhxPBGJxiaeN14+9YmgggjETryMz4JM4VF+J7H5wDmEbOFmEofmb0G7B/0jtJX0i/qBaA/Ow9JDg4JZBr+JfGLRmRmnfl+P0vMgAYspVW5qmHRWXxpKHBmlrvCK+Aw/RKWJ8DiRKn7Dq8LpUpneLYtqd9uBa+CA=
  - secure: BWOZXDSg6t6ie0BWXrMj30wNQlB0IbNJkEV/KOx7rFuNVeBeSUOa69fZ1Kk7fGyhExvMY/CgAMxXIWZGYuFgP2TcITDHhFPOtNDE2k7MTqQDQ6/f4svFR8B7H9Nms0qHmHXc2UXWT+0VNvHCuoMD99zJzG5AP2H68b5um9x6LZPNOrkVwincBOpH1yL2Ed++UCQDoGSN1LjlFOOsGpMD5Q9DRldzAPOI5YqdJkHzmnVyhAbWXbDNkVm7eRqnS4WHe9sNkyAXEd1R3w+TYCaOEHarKFU2w9FqYTAlK0HriVI9BdsowNnaHAERrlwxaqLb7BuEA1j4EkowYClSmCR2tAVJqkTWYTNZXmI/vjJxdap9+PT2kwOkq4ntig7FbcV/NKXVI2ckFgF/NTFvAEoTIWOvIlRvO0Tk7zdSkfR0QnEs4kZ3JeUJpj9wrZ4ISSy6uIh3v9H/cslakAAdkuj0V3J4VGVgih3VllAj8k2mFKWFUBUK4PKmmXMVHZkeTWyqIjm56Jnb+9AaUxmj54IJw50AXqF8eizuYPO55/ZOMPPhqyNqyhCj4hQpipkzYCl25p11AIIzntlgwbEVA7GHdwnGuwXQz2OK0ZZ6QB/8Y05VduSnCB5qsXBo1OKlOSAcEwpM8aLmKcA8ZkjCjVQ3hsCqTe9vz2nTudI1HeK0DOw=
  - secure: jENsu2YACiyzpgN7lvw5CMulJWyC/pO4I9IqEdeDDyWAwnHZ8dTCLolON46YW8hNZnKt0eoynAhCM+noXbseZye22jFrB3dMddDU6b+h62oGbMYuQthAE6y1QGb4e7xBjenBqelCO2di9GVpeQCVotbZcwZG7ZDKij4UTTBJWRz2Xd8siqKQIDIgw6FamIGn34ZfXwI+0YuXiHoagHgV+PIG4zN3ilmAthvvzL0gbuNsuU+Cg+hT0EUnNqHXEeD+jNwUqnS7CD/oGRul0riWN2dE2BzmHGIVp/rAy4pi08Ru9826OzPCeOwYKRt81QkbFFpYtiCghD/6Z0ngrzro4pXdDUPioRyKOoGXA09RuOj6X4C012/NR/45SrCYSQEe+QpF/U82LhXesmVtmbWuNHObPnwcMyY7u3/ibwuG5ZW1XSCB3xle2AU5Cng0BXptqOhMvu9waEcJkzHhiChXiZfdK3eX+y9uNtF0swrgXiHCAXvDvQveUEPnswI8FsfWDKyiF84Q/H61N9TCw/ULc4vNju3Gxl7U0LRfqbCNx6B13NpSpKUBSedsjZvbwYHTvd2dEpDkyyWirHoY0kzY7V5N1YCNFApO9Y20rs0RMfqQQmNe/0Odc4aXoePuhHhCeAuCNXHVlcHlTR+erL8OPP1NSGjUDqDbNWqeiE/EgbU=
  - secure: Qv+bb1LyPkKc8mCBFJRZAcoAUaSQQZd5D5uGAsC1M+SMWnq9iQvbg/txUVZt8eRLGLlvklWO9eWb06iKPCy5oVnh7epjCP/UigA0aOTgwnXosmKv1G/k5o5tj+4wTB3HIziQs514IDZKM6Jtq8plBkacpUiN2BmvuEHTGX3tt9EEwBltPV1DSmrFm+lT7CII/jPHrRuutsegkV+ovwLRChlmYBlsD0RaPh01stPYn3H4AkX5L3c0Q5fVHMD3jgItIY5lcRKfRo3ZYZ8CCI84tBbHA0/r1PEE1hr9aMfOy/VTvf+8A33Y+Qg+ATn85BEh6zrSaRnnXJw3aToCVuFzsubIUchr30DA1et1/cZzTRR3KlcEon7eI5Gim0Y4ELYRBuuaetOin40SGwJXFMoFmyThJhHMdmB5UpLiuU3xZrjAxR+yWLtXCzuawM4JrZSzudBvcfKgG5DkMWPwHuKjfCpjAFHDGTR2qv7/ctn3hyAzfwtw8+Evr/c4p4NaLj1/o2BzAeQdW3EH9j8Eo34yenNNxkMrI+lZ7xuxRIrqHssc6hfsVpX3UTzTgPe/TX89ER/ukUM6p/hpOfWJTgQUBOtqj3Bphq7Tw27Sxrm00jL/y9W3wo/ilYAHUsIHyKB+RCjPl8JBGw2qTwH6llopNuz/aNBkdwmP/DMxSwuJZYw=
  - APP_NAME="Modite-Adventure"
  - PROFILE_NAME="ModiteAdventure"
os:
- linux
- osx
osx_image: xcode12
dist: bionic
language: cpp
git:
  depth: 1
notifications:
  slack:
    secure: XH59GGO2tpCt8reN1DDiuhVtKc6kMhf692Bf01HDPp2iIclvI9NJnbzyrSRpslYbt/3QBX/KNJkVkZh6HevprrWhBCXnn43vDFayh/84I5x43Qpwy+jAix1nhiw60fFkSze3Kuxqhd1u0vl87ahCmKbNkQrMPyom1D5+Ujyi0fcYwDeOLp7pHq+DexEjzCCqu/XtNLUzwB2pTCYmx3XAh8PTIE4LG1WO1uYF2XV2554BLJRIt6mGciR17x63kkCJy2NrJ2Gkve8CTknI1i/aoQWZYQzoJY8MCnpoU4565yt+bVI3eAYVEmimSqt5bai+SBwMeZ8QIZ0qGUfD53tX6C98XHFSeV+GF7TZjBbsS8m00uuuxMGZzD8dxZp9ga7ki0LeLefTGqFZsrLc++NMO0joAQNT55e6kYu/XC05Gg/fAqskGkJSD+tU5Tzhn3DYvYaGe6fIhbg4kX8u8l+Ddd6IrEwQad5G45qovEOi+AXHzM9lOpwOJ7IcBUOsZSZNAkzvonRaN4fhPE/Y5bGlw/qtc8VRN/W2xdVhEheQ67NzzbTgGzeflLe+b3pnKjNxTSMBVuLrlB9jF9PXKNcY0cuMwcqU2ImVLxe9cxlLA+qGIk866tLRRkkUMI5Kjx4S+PpGGcSVVtheEpR0cB2WsH+l17CYXE/xwuDMGpccv14=
before_install:
- chmod +x ./scripts/zipping.sh
- chmod +x ./scripts/code-signing.sh
- chmod +x ./scripts/notarize.sh
- chmod +x ./scripts/add-key.sh
install:
- "./.ci/travis/install_deps.sh"
before_script:
- "./.ci/travis/lint.sh"
- "./scripts/add-key.sh"
script:
- "./scripts/build.sh"
- "./scripts/code-signing.sh"
- "./scripts/test.sh"
after_success:
- "./scripts/code-signing.sh"
before_deploy:
- "./scripts/zipping.sh"
- "./scripts/notarize.sh"
- git tag -f v0.1.0-alpha
deploy:
  provider: releases
  api_key:
    secure: UaqJzNmaL6ctrGEMcqmdO3T7RTUOujTNqDllItA1MdBUZuU7zrJXhvqVuUessfJi1B+rXm2ulWe7PzKjyqYQXVWVg/UoTkn+x47+HX8DHdOTq56V6iiwTXGhh3PnSSSYK809U6vfCS8sYeTIS+yZmguwU1XPLnk/mp8lMyhwK+ASTnRBaNfZlWiWYvsV+qi54ru/X3Ro1WuG/1ckfHDp2batte/dT3rGVbpOJ0mkA4iz5K/M0hPkLTO2Qge/XL2KxqNH/W6XhKgG8XQoi7LpzZLMCOkZzokX/QsDkSlTE40ca/PIv/YenMwbqBofajwBovmaJl0WuzMKJybj+qsAH7Z+7wpQ5fdgC2i5hDqTDf22BzwOu38xezCUS0DnStiqgAvm5NBkfoXyVVphLz0lU635dh+HinTQkW3G+xdhWpuYy7ShP3sdxjsLMW6V4Equ/c6j64BsMWh5Qdxou5aiaPswpqZ3j6ICjtEqeeWvW5+XQLrt5MUpKZVuIFOmL9zD+HQJfWZEEwTjOG0nnuUKQydvfhW7yINS1EmLdgCPoUsKTeScUlWRTHTKXmVqXIeZINQBPl91OiMj725VF+Wjh9pjuAZ3BNEhNd/BCp6JboQv69pTubU1MswZ8ma2LuSN/EstgJvFJ0j0kthso2SJe+5y9VmUEF3b9OvyZQnBoq8=
  file:
  - "/home/travis/build/ModusCreateOrg/modite-adventure/build/modite-linux.zip"
  - "/Users/travis/build/ModusCreateOrg/modite-adventure/build/modite-mac.zip"
  on:
    all_branches: true
  overwrite: true
  skip_cleanup: 'true'
