env:
  global:
  -   secure: "fL6fI2Qx9MGiplTUkQqa3wW9zgcfURQGgDBxqBs80kSFtcz9dos9lsWPcGziSMypBPw6v5hV61hO/YIVIYbxwL9VpiHrweTXX+lHzINQYTmNhOltsgjDCi7TXRaZEIHjK7w0YLZB7PeOnwmoD/0/TAyb1H2rWNJKoSDkBhZrMFKixFurcdhR5J7s6TXYoac6k+Zfp5+xtvOlyG/STp6FXNc32fNHK/XlEqjD4gdWA+IKokkNPDrEZastA7Bqkd2bYF4TezMQSCVznY6zxWodSKiuqGuhFOJUmJ4eWXwg4Zecwlx8dhaRYuciWUqDzWFPihjNwJ5uwwvw0rIsfzylLHtCmw7G9dQlLtgT5/ErmPUh7tQAOPtQ+CFLeKXb33uj3z3KXb9FJbmcbqTaLZj1Se36TuqzALz/fhRu7XJTg/HqU6cyUs+wrroo+52DRwEOmzPGrVT3DTveTzLoDhxT42GCXGJeHSOayqjKb0h4IBTkuHb7sVZ++xUVVKkzsh47izWDnriuOSVWlBiw3QmPr70fCCxLYfWMBqhLGrG6/rZ9sknBEixMxpx5bWiGZ7tzz8Rhk43akooBFnZrZNNQWKq8dZG5p7wEgmS8MCCxRJFC3KIMzYjuxDpB0BBic+P08IbWdPUVQZfq07Mk4z105D0o5U/Wj3N67z9v4n9JS3o="
os:
- linux
- osx 
osx_image: xcode11.2
dist: bionic
language: cpp
sudo: enabled
git:
  depth: 1
install: 
  - sudo pip install --upgrade pip
  - sudo pip install satsuki
  - "./.ci/travis/install_deps.sh"
before_script: "./.ci/travis/lint.sh"
script: "./scripts/build.sh"
notifications:
  slack:
    secure: "I3pds/3UGzKS+ox6cgtnvoEpiSPML8STAZ8qohmxOZv6k+odTl5MaKCHnsbOyGlirIZpqIae1SqyEgFEm++5trWz57+63qv1RAldzCihDAIgWVUGz2EmcNC3I+y4DSNGczbnk3hWArbyAeALGdZpGS/dWPkf3DIVbaWIluhCcnLKz1pVDP3oQwtLzRUQu7xDlxAu0dzTSNPNNv7D1a0yJC1ox0iIckI2s6TrISAeu/XsAbxCApbKTZbAbqcXsxYIF0W1b48k4W00edV/IcokOIDp4hAlh4rLUX9u6h+u5ltjS6rdYNz0Zerm2q8IfvZexh32O3fQV58QeuyZ9G6VYMBtsx+hj/4RgRvL4U/8HVs4f2S3evRr0KbGgiE1v+jY6MXTHhPXitK/uJP82elxruocdQZeJGZpXLQWqhg9kUv8ZSVxCuLvLuvYe9AVpsAdA1+vktVjl596IA7xs4qFwdflBixPCByanTiUp7pSMh9Ijqooefe6Go4cqNJkl06K32aA1kJs36LiiL+eWrnpFE37/CrKIl9bop77i26yRFUhTawnWaDAh86CeZJXHGm3aLI/ZQ7bf9oLR+7jZAG1JrtYxIK2NRPvsfx1SgMdF40chxABzrHKuXtR756WN6YKGKrqLv0OymyiKjcbMXLo8WTk5Xjo/Xb8qejHXeGtPXI="
