env:
  global:
  - secure: "brjVVygD8wy65Go3NKyhGKSXYM9xlKhUjlRk/iXV2wayXLkEoYX7AhIueIMsQMM+jsI8J81jwx3qcHui/yF/Z1V/pbesorOHDg2O8NwTv1QH7Te+VVdNkvHRpNnh3Y83eHh0E/A7LaoTnsDHEiuRkGzKtW8wdrkqU6R9ABv22pRl9M25QXhlkpNT1enUTTrmdvspV8AD9Ex5/scm2fzFo0q+nZ/aIwCNtgchbzEJSIZwEuQ3XZYtVbwHhBeNJaj6Ua24xBXkncxlgszXhEerIaVSzpMBQ1tLvSN4d193l/+vxxHt2iiFRD456h7z7Tkq4vyqb2WQiA80LVM9iVT0cDBGoVroWSNEyw+68fj04f3xQJHFNRW3m1/SrkFnRptrc5p6Is1yQxk79GawOehcCfD3ZosJYyvqSVeUV/rEk9fBznpbsgb6B+EKwemtCfOlMMIXj1DVNgNY0iJUi0oriDrqRBohWi3r1d8F6uNEUocRDYeGWh1risobR3YcDeGgDJm5BpmdSKr24b4jfIMZfSKXJZMtcyJtB/kzJO8pvKdl9V+9Kljg5m4FVL5hLMVS3dRi1tWPrBUwRBkpMXRNsNyGl2h05eU8miNk+UcDuJrC2s14iZpJDQoGZPg9SxdxbcWy9CFfWT6lJVP+RZhUXPHhHHvxE3kN9sd3U8DWCqo="
os:
- linux
- osx 
osx_image: xcode11.2
dist: bionic
language: cpp
sudo: enabled
git:
  depth: 1
install: 
  - sudo pip install --upgrade pip
  - sudo pip install satsuki
  - "./.ci/travis/install_deps.sh"
before_script: "./.ci/travis/lint.sh"
script: "./scripts/build.sh"
notifications:
  slack:
    secure: "XH59GGO2tpCt8reN1DDiuhVtKc6kMhf692Bf01HDPp2iIclvI9NJnbzyrSRpslYbt/3QBX/KNJkVkZh6HevprrWhBCXnn43vDFayh/84I5x43Qpwy+jAix1nhiw60fFkSze3Kuxqhd1u0vl87ahCmKbNkQrMPyom1D5+Ujyi0fcYwDeOLp7pHq+DexEjzCCqu/XtNLUzwB2pTCYmx3XAh8PTIE4LG1WO1uYF2XV2554BLJRIt6mGciR17x63kkCJy2NrJ2Gkve8CTknI1i/aoQWZYQzoJY8MCnpoU4565yt+bVI3eAYVEmimSqt5bai+SBwMeZ8QIZ0qGUfD53tX6C98XHFSeV+GF7TZjBbsS8m00uuuxMGZzD8dxZp9ga7ki0LeLefTGqFZsrLc++NMO0joAQNT55e6kYu/XC05Gg/fAqskGkJSD+tU5Tzhn3DYvYaGe6fIhbg4kX8u8l+Ddd6IrEwQad5G45qovEOi+AXHzM9lOpwOJ7IcBUOsZSZNAkzvonRaN4fhPE/Y5bGlw/qtc8VRN/W2xdVhEheQ67NzzbTgGzeflLe+b3pnKjNxTSMBVuLrlB9jF9PXKNcY0cuMwcqU2ImVLxe9cxlLA+qGIk866tLRRkkUMI5Kjx4S+PpGGcSVVtheEpR0cB2WsH+l17CYXE/xwuDMGpccv14="
