env:
  secure: fZn0UgO43HCCWkJEeL37gwPZylbUngLFxYfVxw23oVJpp2QcksHUJxO1pzgNyTm7GMJl3xxbYa4dK6a72oMsmPsb7xl6jA8L7kQA1Xo+J29QQLxP8WWYP2SyZNxANyyvWpmoMcVnTHZ4UYQMEMiDRNMx4b4iN8ytyQsJj5df9uTOmcr2pNcyTlLTFL1nT43q+MA8nRtKU7sVyDr037CLppxXuY+AUwenCeBHAVpBecfnizRTaItd7qfWYcw27xQZ5Z1M4b6bHWZpwSPdelRsqchLBxIhx50zbBph5xbB4Ov9d6RTcS7J9F3QxMzkCAdT0YuLiIC4TfSZExWUYoOg4/kRm7Vz0LSovmBQMW9FxrKBf7rWoafhqfT83Rz4rssquTICB68U0R4fhUNIctptYgwT2UIfBWGIRwJSGhwsrEnC626uX/bL6B5VslWg2+CjEz1tfqyg88XO/sFcr79IWtVNKuqA/CHu1SCChRlyN9Di7fzvOW7HAAwcnLyCVWNQ9qNjc2c84+ufdhxPBGJxiaeN14+9YmgggjETryMz4JM4VF+J7H5wDmEbOFmEofmb0G7B/0jtJX0i/qBaA/Ow9JDg4JZBr+JfGLRmRmnfl+P0vMgAYspVW5qmHRWXxpKHBmlrvCK+Aw/RKWJ8DiRKn7Dq8LpUpneLYtqd9uBa+CA=
os:
- linux
- osx 
osx_image: xcode11.2
dist: bionic
language: cpp
sudo: enabled
git:
  depth: 1
install: 
  - "./.ci/travis/install_deps.sh"
before_script: "./.ci/travis/lint.sh"
script:
  - "./scripts/build.sh"
  - "./scripts/test.sh"
  - "./scripts/build-ldk.sh"
  - "./scripts/build-upload.sh"
notifications:
  slack:
    secure: "XH59GGO2tpCt8reN1DDiuhVtKc6kMhf692Bf01HDPp2iIclvI9NJnbzyrSRpslYbt/3QBX/KNJkVkZh6HevprrWhBCXnn43vDFayh/84I5x43Qpwy+jAix1nhiw60fFkSze3Kuxqhd1u0vl87ahCmKbNkQrMPyom1D5+Ujyi0fcYwDeOLp7pHq+DexEjzCCqu/XtNLUzwB2pTCYmx3XAh8PTIE4LG1WO1uYF2XV2554BLJRIt6mGciR17x63kkCJy2NrJ2Gkve8CTknI1i/aoQWZYQzoJY8MCnpoU4565yt+bVI3eAYVEmimSqt5bai+SBwMeZ8QIZ0qGUfD53tX6C98XHFSeV+GF7TZjBbsS8m00uuuxMGZzD8dxZp9ga7ki0LeLefTGqFZsrLc++NMO0joAQNT55e6kYu/XC05Gg/fAqskGkJSD+tU5Tzhn3DYvYaGe6fIhbg4kX8u8l+Ddd6IrEwQad5G45qovEOi+AXHzM9lOpwOJ7IcBUOsZSZNAkzvonRaN4fhPE/Y5bGlw/qtc8VRN/W2xdVhEheQ67NzzbTgGzeflLe+b3pnKjNxTSMBVuLrlB9jF9PXKNcY0cuMwcqU2ImVLxe9cxlLA+qGIk866tLRRkkUMI5Kjx4S+PpGGcSVVtheEpR0cB2WsH+l17CYXE/xwuDMGpccv14="
