env:
  global:
  - secure: "l9L49iPoraHOCUb/cheUvROPseJ5fWjyPeQoiHZiZjOLcIUcDsN4H3LbcLf+lF/XsybsJBVSYAua0q/Aay4o46f5xpEQxkUXU7wwGueooMVIqHNyEWQuZA/kH1utjlUVW2i/5hRsVfWlMbqwhoNzHTcVvvcVitOFKhI2dzs4fDxcPXNMAS01OLFLqzre1/CtO3UZbp/6E2ESimCzuXCdd8pDxfW4HKMb8lZQ8ng9ENrT8BWUd9jCYhOXlcTP1yi3dP8tJ4Q9GAuSViPSH9KRq2QNCWXxiyvO5u+xEdDPaau/bHTApyHgByLznurACIvROhmTJv7M2PPQDCQiU7lSG+n/aNWxUTxkXMfZuAX6gFSrroI3xoBeusn7aEVr6kF/8tlUta0Aw1BIoU805jM/24hWqEp/+MTJS2x8clrp2+u7NHq8Jasuj3EyY5RZOivye0+/wJDy2C0Y3PGecAj8Khr4iXuHuC4+eVzThiuQl+LxZPr5RjbwIr4qk2BOd006GzuuQ0QaSbQjkQQuaEQbzhMUvYpSm+tMKP5AcImxafHviTYRc9ac3x7uaDEejM7BgiLlVE7ovLYcN9ZV2eKohFV4HSf1qK61ukC9MB8e/y4lta2rze/B7RkuK4rV2JyeB2jzrNHWT7S5Wi0L79fyiTuaDLOj8ecuZXRx5SeuIic="
os:
- linux
- osx 
osx_image: xcode11.2
dist: bionic
language: cpp
sudo: enabled
git:
  depth: 1
install: 
  - sudo pip install --upgrade pip
  - sudo pip install satsuki
  - "./.ci/travis/install_deps.sh"
before_script: "./.ci/travis/lint.sh"
script: "./scripts/build.sh"
notifications:
  slack:
    secure: "XH59GGO2tpCt8reN1DDiuhVtKc6kMhf692Bf01HDPp2iIclvI9NJnbzyrSRpslYbt/3QBX/KNJkVkZh6HevprrWhBCXnn43vDFayh/84I5x43Qpwy+jAix1nhiw60fFkSze3Kuxqhd1u0vl87ahCmKbNkQrMPyom1D5+Ujyi0fcYwDeOLp7pHq+DexEjzCCqu/XtNLUzwB2pTCYmx3XAh8PTIE4LG1WO1uYF2XV2554BLJRIt6mGciR17x63kkCJy2NrJ2Gkve8CTknI1i/aoQWZYQzoJY8MCnpoU4565yt+bVI3eAYVEmimSqt5bai+SBwMeZ8QIZ0qGUfD53tX6C98XHFSeV+GF7TZjBbsS8m00uuuxMGZzD8dxZp9ga7ki0LeLefTGqFZsrLc++NMO0joAQNT55e6kYu/XC05Gg/fAqskGkJSD+tU5Tzhn3DYvYaGe6fIhbg4kX8u8l+Ddd6IrEwQad5G45qovEOi+AXHzM9lOpwOJ7IcBUOsZSZNAkzvonRaN4fhPE/Y5bGlw/qtc8VRN/W2xdVhEheQ67NzzbTgGzeflLe+b3pnKjNxTSMBVuLrlB9jF9PXKNcY0cuMwcqU2ImVLxe9cxlLA+qGIk866tLRRkkUMI5Kjx4S+PpGGcSVVtheEpR0cB2WsH+l17CYXE/xwuDMGpccv14="
