#include "Game.h"
#include "GPlayerAnimations.h"

const TInt HITSPEED_FIRST = TInt(1.5 * HITSPEED);

/*
 ___    _ _         ______       _           _           _
|_ _|__| | | ___   / / ___|  ___| | ___  ___| |_ ___  __| |
 | |/ _` | |/ _ \ / /\___ \ / _ \ |/ _ \/ __| __/ _ \/ _` |
 | | (_| | |  __// /  ___) |  __/ |  __/ (__| ||  __/ (_| |
|___\__,_|_|\___/_/  |____/ \___|_|\___|\___|\__\___|\__,_|
 */
ANIMSCRIPT idleAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ALABEL,
  ASTEP(40, IMG_IDLE),
  ASTEP(4, IMG_IDLE + 1),
  ASTEP(40, IMG_IDLE + 2),
  ASTEP(4, IMG_IDLE + 1),
  ALOOP
};

ANIMSCRIPT selectedAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ALABEL,
  ASTEP(40, IMG_SELECTED),
  ASTEP(4, IMG_SELECTED + 1),
  ASTEP(40, IMG_SELECTED + 2),
  ASTEP(4, IMG_SELECTED + 1),
  ALOOP
};

/*
 ____
|  _ \  _____      ___ __
| | | |/ _ \ \ /\ / / '_ \
| |_| | (_) \ V  V /| | | |
|____/ \___/ \_/\_/ |_| |_|
*/

ANIMSCRIPT idleDownAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(1, IMG_WALK_DOWN),
  AEND
};

ANIMSCRIPT walkDownAnimation1[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(1,0),
  ASTEP(WALKSPEED, IMG_WALK_DOWN + 1),
  ADELTA(-3, 0),
  ASTEP(WALKSPEED, IMG_WALK_DOWN + 2),
  AEND
};

ANIMSCRIPT walkDownAnimation2[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(-2, 0),
  ASTEP(WALKSPEED, IMG_WALK_DOWN + 3),
  ADELTA(0, 0),
  ASTEP(WALKSPEED, IMG_WALK_DOWN + 0),
  AEND
};

ANIMSCRIPT swordDownAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(-2,0),
  ASTEP(SWORDSPEED, IMG_SWORD_DOWN),

  // this is the frame to collide with enemy to hit it
  ADELTA(-2,22),
  ATYPE(STYPE_PLAYER|STYPE_PBULLET),
  ASIZE(0,23, 32,55),
  ASTEP(SWORDSPEED, IMG_SWORD_DOWN + 1),

  // after the hit frame, reset type to STYPE_PLAYER
  ADELTA(-3,22),
  ASIZE(0,0, 32,32),
  ATYPE(STYPE_PLAYER),
  ASTEP(SWORDSPEED, IMG_SWORD_DOWN + 2),

  ADELTA(-2,7),
  ASTEP(SWORDSPEED, IMG_SWORD_DOWN + 3),
  AEND
};

ANIMSCRIPT hitLightDownAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(HITSPEED_FIRST, IMG_DAMAGE_DOWN+3),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+0),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+1),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+2),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+3),
  AEND
};

ANIMSCRIPT hitMediumDownAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(HITSPEED_FIRST, IMG_DAMAGE_DOWN+3),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+0),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+1),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+2),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+1),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+2),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+3),
  AEND
};

ANIMSCRIPT hitHardDownAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(HITSPEED_FIRST, IMG_DAMAGE_DOWN+3),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+0),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+1),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+2),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+1),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+2),
  ASTEP(HITSPEED, IMG_DAMAGE_DOWN+3),
  AEND
};

/*
 _          __ _
| |    ___ / _| |_
| |   / _ \ |_| __|
| |__|  __/  _| |_
|_____\___|_|  \__|

 */
ANIMSCRIPT idleLeftAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  AFLIP(1, IMG_WALK_RIGHT),
  AEND
};

ANIMSCRIPT walkLeftAnimation1[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(0,0),
  AFLIP(WALKSPEED, IMG_WALK_RIGHT + 1),
  ADELTA(-4,0),
  AFLIP(WALKSPEED, IMG_WALK_RIGHT + 2),
  AEND
};

ANIMSCRIPT walkLeftAnimation2[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(-6,0),
  AFLIP(WALKSPEED, IMG_WALK_RIGHT + 3),
  ADELTA(-4,0),
  AFLIP(WALKSPEED, IMG_WALK_RIGHT + 0),
  AEND
};

ANIMSCRIPT swordLeftAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(-6,0),
  AFLIP(SWORDSPEED, IMG_SWORD_RIGHT),

  ADELTA(-18,0),
  ATYPE(STYPE_PLAYER|STYPE_PBULLET),
  ASIZE(-32, 0, 40,32),
  AFLIP(SWORDSPEED, IMG_SWORD_RIGHT + 1),
  ADELTA(-18,0),
  ATYPE(STYPE_PLAYER),
  ASIZE(0, 0, 32,32),
  AFLIP(SWORDSPEED, IMG_SWORD_RIGHT + 2),
  ADELTA(-9,0),
  AFLIP(SWORDSPEED, IMG_SWORD_RIGHT + 3),
  AEND
};

ANIMSCRIPT hitLightLeftAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  AFLIP(HITSPEED_FIRST, IMG_DAMAGE_RIGHT+3),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+0),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+1),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+2),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+3),
  AEND
};

ANIMSCRIPT hitMediumLeftAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  AFLIP(HITSPEED_FIRST, IMG_DAMAGE_RIGHT+3),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+0),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+1),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+2),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+1),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+2),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+3),
  AEND
};


ANIMSCRIPT hitHardLeftAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  AFLIP(HITSPEED_FIRST, IMG_DAMAGE_RIGHT+3),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+0),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+1),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+2),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+1),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+2),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+3),
  AEND
};

/*
 ____  _       _     _
|  _ \(_) __ _| |__ | |_
| |_) | |/ _` | '_ \| __|
|  _ <| | (_| | | | | |_
|_| \_\_|\__, |_| |_|\__|
         |___/
 */
ANIMSCRIPT idleRightAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(1, IMG_WALK_RIGHT),
  AEND
};

ANIMSCRIPT walkRightAnimation1[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(0,0),
  ASTEP(WALKSPEED, IMG_WALK_RIGHT),
  ADELTA(4,0),
  ASTEP(WALKSPEED, IMG_WALK_RIGHT + 1),
  AEND
};

ANIMSCRIPT walkRightAnimation2[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(6,0),
  ASTEP(WALKSPEED, IMG_WALK_RIGHT + 2),
  ADELTA(4,0),
  ASTEP(WALKSPEED, IMG_WALK_RIGHT + 3),
  AEND
};

ANIMSCRIPT swordRightAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(8,0),
  ASTEP(SWORDSPEED, IMG_SWORD_RIGHT),

  ADELTA(20,0),
  ATYPE(STYPE_PLAYER|STYPE_PBULLET),
  ASIZE(16, 0, 72,32),
  ASTEP(SWORDSPEED, IMG_SWORD_RIGHT + 1),

  ADELTA(20,0),
  ATYPE(STYPE_PLAYER),
  ASIZE(0, 0, 32,32),
  ASTEP(SWORDSPEED, IMG_SWORD_RIGHT + 2),
  ADELTA(11,0),
  ASTEP(SWORDSPEED, IMG_SWORD_RIGHT + 3),
  AEND
};

ANIMSCRIPT hitLightRightAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(HITSPEED_FIRST, IMG_DAMAGE_RIGHT+3),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+0),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+1),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+2),
  AFLIP(HITSPEED, IMG_DAMAGE_RIGHT+3),
  AEND
};

ANIMSCRIPT hitMediumRightAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(HITSPEED_FIRST, IMG_DAMAGE_RIGHT+3),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+0),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+1),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+2),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+1),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+2),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+3),
  AEND
};

ANIMSCRIPT hitHardRightAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(HITSPEED_FIRST, IMG_DAMAGE_RIGHT+3),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+0),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+1),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+2),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+1),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+2),
  ASTEP(HITSPEED, IMG_DAMAGE_RIGHT+3),
  AEND
};

/*
 _   _
| | | |_ __
| | | | '_ \
| |_| | |_) |
 \___/| .__/
      |_|
 */
ANIMSCRIPT idleUpAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(1, IMG_WALK_UP),
  AEND
};

ANIMSCRIPT walkUpAnimation1[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(-2, 0),
  ASTEP(WALKSPEED, IMG_WALK_UP + 1),
  ADELTA(-7, 0),
  ASTEP(WALKSPEED, IMG_WALK_UP + 2),
  AEND
};

ANIMSCRIPT walkUpAnimation2[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(-1, 0),
  ASTEP(WALKSPEED, IMG_WALK_UP + 3),
  ADELTA(0, 0),
  ASTEP(WALKSPEED, IMG_WALK_UP + 0),
  AEND
};

ANIMSCRIPT swordUpAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ADELTA(4,-2),
  ASTEP(SWORDSPEED, IMG_SWORD_UP),

  ADELTA(2,-2),
  ATYPE(STYPE_PLAYER|STYPE_PBULLET),
  ASIZE(0, 0, 32,58),
  ASTEP(SWORDSPEED, IMG_SWORD_UP + 1),

  ADELTA(4,-2),
  ATYPE(STYPE_PLAYER),
  ASIZE(0, 0, 32,32),
  ASTEP(SWORDSPEED, IMG_SWORD_UP + 2),

  ADELTA(-2,-2),
  ASTEP(SWORDSPEED, IMG_SWORD_UP + 3),
  AEND
};

ANIMSCRIPT hitLightUpAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(HITSPEED_FIRST, IMG_DAMAGE_UP+3),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+0),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+1),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+2),
  AFLIP(HITSPEED, IMG_DAMAGE_UP+3),
  AEND
};

ANIMSCRIPT hitMediumUpAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(HITSPEED_FIRST, IMG_DAMAGE_UP+3),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+0),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+1),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+2),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+1),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+2),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+3),
  AEND
};


ANIMSCRIPT hitHardUpAnimation[] = {
  ABITMAP(PLAYER_SLOT),
  ASTEP(HITSPEED_FIRST, IMG_DAMAGE_UP+3),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+0),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+1),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+2),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+1),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+2),
  ASTEP(HITSPEED, IMG_DAMAGE_UP+3),
  AEND
};




