#ifndef MODITE_ITEMS_H
#define MODITE_ITEMS_H

static const TInt items[] = {
  0,                    // 0 = no item
  IMG_BLUE_SPELLBOOK,
  IMG_RED_SPELLBOOK,
  IMG_GREEN_SPELLBOOK,
  IMG_YELLOW_SPELLBOOK,
  IMG_SILVER_KEY,
  IMG_GOLD_KEY,
  IMG_BLUE_RING,
  IMG_RED_RING,
  IMG_GREEN_RING,
  IMG_YELLOW_RING,
  IMG_BOOTS,
  IMG_GLOVES,
  IMG_SWORD,
  IMG_BLUE_AMULET,
  IMG_RED_AMULET,
  IMG_GREEN_AMULET,
  IMG_YELLOW_AMULET,
  IMG_GREEN_POTION1,
  IMG_GREEN_POTION2,
  IMG_BLUE_POTION1,
  IMG_BLUE_POTION2,
  IMAGE_EMPTY_BOTTLE,
  IMG_BLUE_BOTTLE1,
  IMG_BLUE_BOTTLE2,
  IMG_BLUE_BOTTLE3,
  IMG_BLUE_BOTTLE4,
  IMG_GREEN_BOTTLE1,
  IMG_GREEN_BOTTLE2,
  IMG_GREEN_BOTTLE3,
  IMG_GREEN_BOTTLE4,
};

static const char *itemNames[] = {
  "INVALID ITEM",
  "Blue Spellbook",
  "Red Spellbook",
  "Green Spellbook",
  "Yellow Spellbook",
  "Silver Key",
  "Gold Key",
  "Blue Ring",
  "Red Ring",
  "Green Ring",
  "Yellow Ring",
  "Boots",
  "Gloves",
  "Sword",
  "Blue Amulet",
  "Red Amulet",
  "Green Amulet",
  "Yellow Amulet",
  "Small Green Potion",
  "Big Green Potion",
  "Small Blue Potion",
  "Big Blue Potion",
  "Empty Bottle",
  "Blue Bottle 25%",
  "Blue Bottle 50%",
  "Blue Bottle 75%",
  "Blue Bottle Full",
  "Green Bottle 25%",
  "Green Bottle 50%",
  "Green Bottle 75%",
  "Green Bottle Full",
};

#endif //MODITE_ITEMS_H
